services:
  backend:
    container_name: ${APP_NAME}
    build: ./backend/.
    image: ${APP_NAME}
    volumes:
      - ./backend/:/build
    ports:
      - 8080:8080
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql
    networks:
      - go-network

  mysql:
    container_name: go-mysql
    build: ./database/.
    image: go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - go-network

  frontend:
    container_name: go-front
    image: node:jod-slim
    working_dir: /app
    volumes:
      - ./frontend/:/app
    ports:
      - 3000:5173
    networks:
      - go-network
    depends_on:
      - backend
    tty: true
    stdin_open: true
    entrypoint: [ 'npm', 'run', 'dev' ]

volumes:
  dbdata:


networks:
  go-network:
    driver: bridge
